### ISSUE TITLE
Mess with coordinates in query with $near operator

### ISSUE THREAD

**Issue by xphoenyx** [Sammaye/MongoYii#243] opened 2014-12-15 00:02 UTC
I'm trying to get all objects around some point using $near, including some user input (search). In my action, query goes like this:
```php
MyModel::model()->near(array(59.4374929, 24.8294359))->userSearch('text');
```
where `near()` is a scope that includes $near statement with given coordinates in query condition and `userSearch()` is constructing a search conditoin with given argument, merges it with condition from `near()` scope and then should return `EMongoDataProvider` with whole condition, but instead of it the `MongoException` is thrown:
```php
Cannot run command count(): exception: $near requires a point, given { type: "Point", coordinates: [ 59.4374929, 24.8294359, 59.4374929, 24.8294359 ] }
```
It can be seen that coordinates are duplicating. I didn't got a time to investigate subject better yet, but I can truly say that this is not my code fault: array that is passes to `near()` as an argument is checked and any duplications are excluded. Could it be a `mongoyii` extension issue, or is it an ActiveDataProvider/Criteria/ActiveRecord feature?

**Comment by xphoenyx** [comment] 2015-01-02 06:18
Thanx for this advice. I'm trying to find out the best approach to merge all conditions to use in query just to avoid the problem I have mentioned in my first post. I tried your example, and it works well until `$near` operator passes to condition. Believe it or not, mongo throws the same error message:

    Cannot run command count(): exception: $near requires a point, given { type: "Point", coordinates: [ 59.43752550000001, 24.8294116, 59.4375255, 24.8294116 ] } (/home/xphoenyx/htdocs/yii-places/project/protected/extensions/mongoyii/EMongoCursor.php:211) #0 /home/xphoenyx/htdocs/yii-places/project/protected/extensions/mongoyii/EMongoCursor.php(211): MongoCursor->count(false)

even in this case:

```php
$dp = new EMongoDataProvider(get_called_class(), array(
    'criteria'=>array(
        'condition'=>array('loc'=>array('$near' => array('$geometry'=>array('type'=>'Point', 'coordinates'=>array(59.4375255, 24.8294116)))));
    ),
    'pagination' => false
));

return $dp;
```

Do you have any suggestions?

**Comment by Sammaye** [comment] 2015-01-03 20:32
I notice: `[ 59.43752550000001, 24.8294116, 59.4375255, 24.8294116 ]` that there is no duplication. There is something funny going on in your code somewhere that is causing a merging of array parts of existing queries

**Comment by Sammaye** [comment] 2015-01-03 20:33
P.S sorry about the lateness, my hands are quite full currently

**Comment by xphoenyx** [comment] 2015-01-04 01:36
Actually, accuracy of longitude or latitude is not necessary. No matter what coordinates in $near I pass to the `EMongoDataProvider`, the exception is thrown. Although I can print an instance of it before one arrives to the `CListView`.
Don't worry, it's OK. I appreciate your help.

**Comment by Sammaye** [comment] 2015-01-06 08:19
Can you give me a full example? Bring it down as much as possible to a basic set of classes which replicate the problem since I cannot seem to replicate this when I try it.

**Comment by xphoenyx** [comment] 2015-01-06 08:49
Sure.

I have a controller action. which shows a list of places:

```php
public function actionList() {
        $category = Yii::app()->request->getParam('category');
        $subCategory = Yii::app()->request->getParam('subCategory');

        $model = Places::model()->safe();
        if(isset($_COOKIE['user_coords']))
            $model = $model->near($_COOKIE['user_coords']);

        $dataProvider = $model->searchByCategory($category, $subCategory);
        $this->render('list', array('dataProvider'=>$dataProvider));
}
```
Here, `$_COOKIE['user_coords']` is a string with longitude and latitude divided by comma. Now, to the `Places` model methods.

Scope `safe`:

```php
public function scopes() {
    return array(
        'safe'=>array(
            'condition'=>array('$or'=>array(array('status'=>'accepted'), array('status'=>'unverified'))),
        )
    );
}
```

Scope `near`:

```php
public function near($lonLat) {
    if(is_string($lonLat)) {
        $lonLat = explode(',', $lonLat);
        $lonLat = array_map(function($val) {return (float)$val;}, $lonLat);
    }
    
    if(is_array($lonLat) && count($lonLat) == 2 && is_double($lonLat[0]) && is_double($lonLat[1])) {
        $condition['loc'] = array('$near' => array('$geometry'=>array('type'=>'Point', 'coordinates'=>$lonLat)));

        $this->mergeDbCriteria(array(
            'condition'=>$condition
        ));
    }

    return $this;
}
```

And finally, searching method `searchByCategory`:

```php
public function searchByCategory($cat=null, $subCat=null) {
    $condition = array();

    if($cat && $cat != 'all' && Categories::isCategory($cat))
        $condition['category'] = $cat;
    if($subCat && $subCat != 'all' && Categories::isCategory($cat, $subCat))
        $condition['subCategory'] = $subCat;

    $dp = new PlacesDataProvider(get_called_class(), array(
        'criteria'=>array(
            'condition'=>$this->mergeConditions($condition)
        ),
        'pagination' => false
    ));

    return $dp;
}
```

Here, `mergeConditions` method looks like this:

```php
private function mergeConditions($condition) {
    return CMap::mergeArray($condition, $this->getDbCriteria()['condition']);
}
```

In `list` view, I use `$dataProvider` like this:

```php
$this->widget('zii.widgets.CListView', array(
    'dataProvider'=>$dataProvider,
    'itemView'=>'_place',
    'template'=>'{items}',
));
```

That is enough for me to cause a problem. Hope the code is comprehensive.

**Comment by Sammaye** [comment] 2015-01-11 14:30
I think this will take for me to build a program with this code but I am currently finding it hard to find 5 mins to myself to do exactly that

**Comment by xphoenyx** [comment] 2015-01-20 17:01
I just prepared a fully set up app with a bug reproduction: https://github.com/xphoenyx/mongo-bug. But during it, with help of colleague of mine, I realised that problem arises when [merging conditions from model and criteria objects](https://github.com/xphoenyx/mongo-bug/blob/master/protected/vendor/mongoyii/EMongoDocument.php#L912). The php function `array_merge` simply does not merge indexed arrays, which gives an array with 4 values (two latitudes and 2 longitudes) instead of 2 as a result. As a quick solution - compare indexed arrays by values, not keys.

**Comment by Sammaye** [comment] 2015-01-21 17:57
Odd, mergeArray ( https://github.com/xphoenyx/mongo-bug/blob/master/protected/vendor/mongoyii/EMongoDocument.php#L1450 ) should merge keys can you give full work out of it and I will try and find time tomorrow to setup something, I think I will actually have some time tomorrow

**Comment by xphoenyx** [comment] 2015-01-21 23:56
You are very welcome to use source from my repo. The application is fully working, just download it, set up a DB connection, import some data and here you go

**Comment by Sammaye** [comment] 2015-01-22 14:26
Roger, replicated; investigating now

**Comment by Sammaye** [comment] 2015-01-22 14:37
You are right about the array merging, though it is because for some reason Yii1 is not recursively meging the arrays right

**Comment by Sammaye** [comment] 2015-01-22 14:46
Ah ffs:

```php
	/**
	 * Merges two or more arrays into one recursively.
	 * If each array has an element with the same string key value, the latter
	 * will overwrite the former (different from array_merge_recursive).
	 * Recursive merging will be conducted if both arrays have an element of array
	 * type and are having the same key.
	 * For integer-keyed elements, the elements from the latter array will
	 * be appended to the former array.
	 * @param array $a array to be merged to
	 * @param array $b array to be merged from. You can specify additional
	 * arrays via third argument, fourth argument etc.
	 * @return array the merged array (the original arrays are not changed.)
	 * @see mergeWith
	 */
```

paying attention to: 

```php
	 * For integer-keyed elements, the elements from the latter array will
	 * be appended to the former arra
```

**Comment by Sammaye** [comment] 2015-01-22 15:08
The problem is that I am concerned that others might actually rely on this behaviour now.

I must admit I am unsure what keys to merge and append in a numeric array as well.

You can immediately solve this by adding:

   $this->setDbCriteria([]);

to the end of the `searchByCategory` just before it's `return`.

As for something in the long run...I am unsure if it will break someone elses code or not so I am a bit skeptical about implementing it.

So long as you null the moels DbCriteria beofre using that instance of the model in a dataprovider.

I believe I know why this is happening irrespectively of your use of get_called_class(). Yii1 caches the model instances ( https://github.com/yiisoft/yii/blob/master/framework/db/ar/CActiveRecord.php#L55 ) for use later and it just so happens that the one it caches is the one with all the condition in it. This means that wehn you come to pick a class via `::model()` you infact pick the instance with the conditions so you effectively merge two full conditions together resulting in the duplication.

**Comment by xphoenyx** [comment] 2015-01-22 18:14
Thank you very much, it is absolutely clear for me now, why this is happening. Really, I should read method descriptions more carefully. Just a concept: to create a validation methods for different mongo operators. Corresponding validation should be performed automatically, if any of the operators is used in query. Although it would be not so good approach in terms of performance.
Anyways, as this might be not only my problem, maybe I can leave this issue open for a while?

**Comment by Sammaye** [comment] 2015-01-22 18:24
Sure, in fact there might be a bug in that the ::model function is picking a class that has scopes populated, not sure if it should actually.

**Comment by Sammaye** [comment] 2015-03-21 22:50
Okay, since it has been a month since any breakage I am gonna close this for the min to clean up my todo list (I think I may have some kind of behavioral condition that makes me clean anything too old).

Feel free to reopen if things change.

**Closed by Sammaye** 2015-03-21 22:50 UTC

**Comment by xphoenyx** [comment] 2015-03-27 23:56
Thank you once again!
